name: lint
on:
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      # Action Repo: https://github.com/actions/checkout
      - name: 'Checkout repo'
        uses: actions/checkout@v2

      # Action Repo: https://github.com/actions/setup-node
      - name: 'Setup Node'
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      # Action Repo: https://github.com/actions/cache
      - name: 'Cache node_modules'
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}

      - name: 'Install'
        run: npm ci

      - name:
        run: npm run lint
